model: "/home/ssu/Qwen2.5-7B-Instruct"
no-enable-prefix-caching: false
tensor-parallel-size: 1
data-parallel-size: 1
block-size: 128
enforce_eager: true
max-num-batched-tokens: 32000
port: 8100
max-model-len: 32000
kv-transfer-config: '{
    "kv_connector": "AscendStoreConnector",
    "kv_role": "kv_both",
    "kv_connector_extra_config": {
        "lookup_rpc_port": "1",
        "backend": "mooncake",
        "use_layerwise": false,
        "mooncake_rpc_port": "0",
        "load_async": true,
        "register_buffer": true
    }
}'